EMAIL_SERVICE_MAILJET = "mailjet"
EMAIL_SERVICE_CHOICES = ((EMAIL_SERVICE_MAILJET, "Mailjet"),)

DEFAULT_EMAIL_SERVICE = EMAIL_SERVICE_MAILJET

EMAIL_RECIPIENT_TYPE_TO = "to"
EMAIL_RECIPIENT_TYPE_CC = "cc"
EMAIL_RECIPIENT_TYPE_BCC = "bcc"

EMAIL_RECIPIENT_TYPE_CHOICES = (
    (EMAIL_RECIPIENT_TYPE_TO, "To"),
    (EMAIL_RECIPIENT_TYPE_CC, "Cc"),
    (EMAIL_RECIPIENT_TYPE_BCC, "Bcc"),
)

DEFAULT_FROM_EMAIL = "test@gmail.com"
