"""
FIle contains constants for email_scheduler app
"""

EMAIL_SERVICE_MAILJET = "mailjet"
EMAIL_SERVICE_CHOICES = ((EMAIL_SERVICE_MAILJET, "Mailjet"), )

DEFAULT_EMAIL_SERVICE = EMAIL_SERVICE_MAILJET

TASK_STATUS_PENDING = "pending"
TASK_STATUS_COMPLETE = "complete"
TASK_STATUS_FAILED = "failed"

TASK_STATUS_CHOICES = (
    (TASK_STATUS_PENDING, "Pending"),
    (TASK_STATUS_COMPLETE, "Complete"),
    (TASK_STATUS_FAILED, "Failed"),
)

EMAIL_RECIPIENT_TYPE_TO = "to"
EMAIL_RECIPIENT_TYPE_CC = "cc"
EMAIL_RECIPIENT_TYPE_BCC = "bcc"

EMAIL_RECIPIENT_TYPE_CHOICES = (
    (EMAIL_RECIPIENT_TYPE_TO, "To"),
    (EMAIL_RECIPIENT_TYPE_CC, "Cc"),
    (EMAIL_RECIPIENT_TYPE_BCC, "Bcc"),
)

EMAIL_SEND_STATUS_SUCCESS = "success"
EMAIL_SEND_STATUS_ERROR = "error"

DEFAULT_FROM_EMAIL = "test@gmail.com"
